apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-green-blue
  labels:
    deployment-type: blue-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-web-bg  # Different app name
      version: blue
  template:
    metadata:
      labels:
        app: my-web-bg  # Different
        version: blue
        deployment-type: blue-green
    spec:
      containers:
      - name: hello-container
        image: acavinash/blue:v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-green-green
  labels:
    deployment-type: blue-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-web-bg  # Different
      version: green
  template:
    metadata:
      labels:
        app: my-web-bg  # Different
        version: green
        deployment-type: blue-green
    spec:
      containers:
      - name: hello-container
        image: acavinash/green:v1
---
apiVersion: v1
kind: Service
metadata:
  name: blue-green-service
  labels:
    deployment-type: blue-green
spec:
  type: LoadBalancer
  selector:
    app: my-web-bg  # Different
    version: blue  # Blue-green specific
  ports:
    - port: 80
      targetPort: 80